// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `register`, `registry`, `unregister`

class LiveQueryManager {
  const LiveQueryManager();

  /// Kills a live query task by one-time abort.
  static Future<void> kill({required String uuid}) => RustLib.instance.api
      .crateApiLiveQueryManagerLiveQueryManagerKill(uuid: uuid);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveQueryManager && runtimeType == other.runtimeType;
}
