// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

enum LiveQueryAction { create, update, delete, snapshot, unknown }

class LiveQueryEvent {
  final LiveQueryAction action;
  final String result;
  final String? id;
  final String? queryUuid;

  const LiveQueryEvent({
    required this.action,
    required this.result,
    this.id,
    this.queryUuid,
  });

  static Future<LiveQueryEvent> handshake({required String queryUuid}) =>
      RustLib.instance.api.crateApiLiveQueryModelsLiveQueryEventHandshake(
        queryUuid: queryUuid,
      );

  @override
  int get hashCode =>
      action.hashCode ^ result.hashCode ^ id.hashCode ^ queryUuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveQueryEvent &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          result == other.result &&
          id == other.id &&
          queryUuid == other.queryUuid;
}
