// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_and_send`

Stream<LiveQueryEvent> runLiveQueryLoop({
  required SurrealAny db,
  required String tableName,
  required String queryUuid,
}) => RustLib.instance.api.crateApiLiveQueryStreamRunLiveQueryLoop(
  db: db,
  tableName: tableName,
  queryUuid: queryUuid,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Surreal < Any >>>
abstract class SurrealAny implements RustOpaqueInterface {}
