// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'live_query/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'client.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_dir_exists`, `get_client`, `graceful_shutdown`, `kill_zombie_processes`, `spawn_sidecar_server`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServerGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SurrealDb>>
abstract class SurrealDb implements RustOpaqueInterface {
  Future<void> authenticate({required String token});

  Future<void> close();

  static Future<SurrealDb> connect({required StorageMode mode}) =>
      RustLib.instance.api.crateApiClientSurrealDbConnect(mode: mode);

  /// Starts a pure Live Query Stream (No Snapshot) - Legacy/Standard behavior
  Stream<LiveQueryEvent> connectLiveQuery({required String table});

  /// Starts a Live Query Stream WITH an initial Snapshot of the table
  Stream<LiveQueryEvent> connectLiveQueryWithSnapshot({required String table});

  Future<String> create({required String resource, String? data});

  Future<String> delete({required String resource});

  Future<void> export_({required String path});

  Future<void> invalidate();

  static Future<void> killQuery({required String queryUuid}) => RustLib
      .instance
      .api
      .crateApiClientSurrealDbKillQuery(queryUuid: queryUuid);

  Stream<LiveQueryEvent> liveQuery({required String tableName});

  Future<String> merge({required String resource, String? data});

  Future<String> query({required String sql, String? vars});

  Future<void> queryBegin();

  Future<void> queryCancel();

  Future<void> queryCommit();

  Future<String> queryTyped({required String sql, String? vars});

  Future<String> select({required String resource});

  Future<String> signin({required String creds});

  Future<String> signup({required String creds});

  Future<String> transaction({required String stmts, String? vars});

  Future<String> update({required String resource, String? data});

  Future<void> useDb({required String ns, required String db});
}

@freezed
sealed class StorageMode with _$StorageMode {
  const StorageMode._();

  const factory StorageMode.memory() = StorageMode_Memory;
  const factory StorageMode.disk({required String path}) = StorageMode_Disk;
  const factory StorageMode.remote({required String url}) = StorageMode_Remote;

  /// Starts a local sidecar server connection (Desktop only)
  const factory StorageMode.devSidecar({
    required String path,
    required int port,
  }) = StorageMode_DevSidecar;
}
