// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A strict representation of a SurrealDB Record ID.
/// Naming matches the standard `RecordId` expectation.
class RecordId {
  final String tb;
  final String id;

  const RecordId({required this.tb, required this.id});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RecordId> newInstance({
    required String tb,
    required String id,
  }) => RustLib.instance.api.crateApiModelsRecordIdNew(tb: tb, id: id);

  @override
  String toString() =>
      RustLib.instance.api.crateApiModelsRecordIdToString(that: this);

  @override
  int get hashCode => tb.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordId &&
          runtimeType == other.runtimeType &&
          tb == other.tb &&
          id == other.id;
}
