// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'live_query/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Connects to a Live Query, ensuring no data loss by starting the stream BEFORE fetching the snapshot.
/// Returns the snapshot and the query UUID.
/// The stream events are sent to the provided `sink`.
/// Connects to a Live Query, ensuring no data loss by starting the stream BEFORE fetching the snapshot.
/// Returns Ok(()) and streams events (Snapshot -> Handshake -> Updates) to `sink`.
Stream<LiveQueryEvent> connectLiveQuery({
  required SurrealAny db,
  required String table,
}) =>
    RustLib.instance.api.crateApiRealtimeConnectLiveQuery(db: db, table: table);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Surreal < Any >>>
abstract class SurrealAny implements RustOpaqueInterface {}
